# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171031_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cteated_time',
            new_name='created_time',
        ),
    ]
